/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employee.oop;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author nradl
 */
public class AddEmployee extends javax.swing.JFrame {

    public static int id = 1111;
    public static int notel = 0;
    JFrame f = new JFrame();

    public AddEmployee() {
        initComponents();
        
        //drop down menu items
        myConnection();
        String query = "select DepartCode from Department";
        try {
            Statement statement = conn.createStatement();
            ResultSet rs = statement.executeQuery(query);
            while(rs.next()){
                String code = rs.getString("DepartCode");
                departcodelist.addItem(code);
            }
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // Display ID in field and set uneditable
        EmployeeID.setText(Integer.toString(id));
        EmployeeID.setEditable(false);
    }
    
    Connection conn;
    PreparedStatement pstmt;
    ResultSet rs;

    public void myConnection() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/oop?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "");
        } catch (SQLException ex) {
            Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        MainMenu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        EmployeeName = new javax.swing.JTextField();
        EmployeeID = new javax.swing.JTextField();
        departcodelist = new javax.swing.JComboBox<>();
        Location = new javax.swing.JTextField();
        NameMsg = new javax.swing.JTextField();
        LocationMsg = new javax.swing.JTextField();
        DepartName = new javax.swing.JTextField();
        empdesignation = new javax.swing.JComboBox<>();
        DesignMsg = new javax.swing.JTextField();
        DepartCodeMsg = new javax.swing.JTextField();
        DesignName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(77, 137, 99));

        jLabel1.setBackground(new java.awt.Color(77, 137, 99));
        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EMPLOYEE INFORMATION SYSTEM");

        jPanel2.setBackground(new java.awt.Color(224, 204, 151));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add an Employee");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Submit.setBackground(new java.awt.Color(236, 121, 154));
        Submit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        MainMenu.setBackground(new java.awt.Color(236, 121, 154));
        MainMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MainMenu.setText("Go Back");
        MainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenuActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Enter Employee Name :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Employee ID :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Department Code :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Designation :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Enter Location :");

        EmployeeName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EmployeeNameKeyPressed(evt);
            }
        });

        EmployeeID.setEditable(false);
        EmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeIDActionPerformed(evt);
            }
        });

        departcodelist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        departcodelist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departcodelistActionPerformed(evt);
            }
        });

        NameMsg.setEditable(false);
        NameMsg.setBackground(new java.awt.Color(77, 137, 99));
        NameMsg.setBorder(null);

        LocationMsg.setEditable(false);
        LocationMsg.setBackground(new java.awt.Color(77, 137, 99));
        LocationMsg.setBorder(null);

        DepartName.setEditable(false);
        DepartName.setBackground(new java.awt.Color(77, 137, 99));
        DepartName.setBorder(null);

        empdesignation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "O", "C", "E" }));
        empdesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empdesignationActionPerformed(evt);
            }
        });

        DesignMsg.setEditable(false);
        DesignMsg.setBackground(new java.awt.Color(77, 137, 99));
        DesignMsg.setBorder(null);

        DepartCodeMsg.setEditable(false);
        DepartCodeMsg.setBackground(new java.awt.Color(77, 137, 99));
        DepartCodeMsg.setBorder(null);

        DesignName.setEditable(false);
        DesignName.setBackground(new java.awt.Color(77, 137, 99));
        DesignName.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Submit)
                .addGap(55, 55, 55)
                .addComponent(MainMenu)
                .addGap(146, 146, 146))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Location)
                            .addComponent(EmployeeName)
                            .addComponent(EmployeeID)
                            .addComponent(departcodelist, 0, 300, Short.MAX_VALUE)
                            .addComponent(empdesignation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DesignName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LocationMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DepartName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DesignMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DepartCodeMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(EmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DepartName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(departcodelist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DepartCodeMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empdesignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DesignMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LocationMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DesignName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit)
                    .addComponent(MainMenu))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // for getting all the fields' value
        String name = EmployeeName.getText();
        String dcode = departcodelist.getSelectedItem().toString();
        String loc = Location.getText();
        String dsign = empdesignation.getSelectedItem().toString();

        // flags for validation prior to submission
        boolean namecheck, dcodecheck, loccheck, dsigncheck;
        namecheck = dcodecheck = loccheck = dsigncheck = false;

        // Validates employee's name
        if (name.isBlank()) {
            NameMsg.setText("Please enter the employee's name.");
            NameMsg.setForeground(Color.RED);
        } else if (name.length() < 3) {
            NameMsg.setText("Name must have at least 3 characters.");
            NameMsg.setForeground(Color.RED);
        } else if (name.length() > 25) {
            NameMsg.setText("Name cannot exceed 25 characters.");
            NameMsg.setForeground(Color.RED);
        } else if (!Character.isUpperCase(name.charAt(0))) {
            NameMsg.setText("First character must be in upper case.");
            NameMsg.setForeground(Color.RED);
        } else {
            namecheck = true;
            NameMsg.setText("");
        }

        // Validates department code
        if (dcode.equals("Select")) {
            DepartName.setText("Please select a department code.");
            DepartName.setForeground(Color.red);
        } else {
            dcodecheck = true;
            DepartName.setText("");
        }

        // Validates Location
        if (loc.isBlank()) {
            LocationMsg.setText("Please enter a location.");
            LocationMsg.setForeground(Color.red);
        } else if (loc.length() < 3) {
            LocationMsg.setText("Location name must have at least 3 characters.");
            LocationMsg.setForeground(Color.red);
        } else if (loc.length() > 5) {
            LocationMsg.setText("Location name cannot exceed 5 characters.");
            LocationMsg.setForeground(Color.red);
        } else {
            loccheck = true;
            LocationMsg.setText("");
        }

        // Validates employee designation 
        if (dsign.equals("Select")) {
            DesignMsg.setText("Please select a designation.");
            DesignMsg.setForeground(Color.red);
        } else {
            dsigncheck = true;
            DesignMsg.setText("");
        }

        // Validation before submission (all must be TRUE)
        if (namecheck && dcodecheck && loccheck && dsigncheck) {

            myConnection();
            String query1 = "Select EmployeeID from Employee";
            String query2 = "insert into Employee (EmployeeID, EmployeeName, " + "EmployeeDepartCode, EmployeeLocation, EmployeeTelNum, " + "EmployeeDesignation) value (?, ?, ?, ?, ?, ?)";

            // Check if there's an existing ID assigned
            try {
                PreparedStatement statement1 = conn.prepareStatement(query1);
                ResultSet rs = statement1.executeQuery(query1);
                while (rs.next()) {
                    int idcheck = rs.getInt("EmployeeID");
                    if (idcheck == id) {
                        id++;
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }

            // adding the data into the table (Submission)
            try {
                PreparedStatement statement2 = conn.prepareStatement(query2);
                statement2.setInt(1, id);
                statement2.setString(2, name);
                statement2.setString(3, dcode);
                statement2.setString(4, loc);
                statement2.setInt(5, notel);
                statement2.setString(6, dsign);
                statement2.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Employee Successfully Added!");
                id++; // ID number auto increments after sucessfully submission
                conn.close();

                // Back to Employee Maintanence after submission
                EmployeeMM page = new EmployeeMM();
                page.setVisible(true);
                setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }

        } // Display error message if unsuccessful at register (blanks)
        else {
            JOptionPane.showMessageDialog(rootPane, "Registration Unsuccessful.\n"
                    + "Check the field message for more info.");
        }
    }//GEN-LAST:event_SubmitActionPerformed

    private void MainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuActionPerformed
        // TODO add your handling code here:
        new EmployeeMM().setVisible(true);
        dispose();
    }//GEN-LAST:event_MainMenuActionPerformed

    private void departcodelistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departcodelistActionPerformed
        // Displaying Department name after selecting department code
        myConnection();
        try {
            String query="SELECT DepartName FROM department WHERE DepartCode ='"
            + departcodelist.getSelectedItem().toString() + "'";
            PreparedStatement statement =conn.prepareStatement(query);
            ResultSet rs = statement.executeQuery(query);
            if(rs.next()){
                DepartName.setText("Deparment: " + rs.getString("DepartName"));

            }else{
                DepartName.setText("");
            }
            conn.close();
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_departcodelistActionPerformed

    private void EmployeeNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmployeeNameKeyPressed


    }//GEN-LAST:event_EmployeeNameKeyPressed

    private void empdesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empdesignationActionPerformed
        // Displaying Designation name after selection
        switch (empdesignation.getSelectedItem().toString()) {
            case "O" ->
                DesignName.setText("Position: HR Officer");
            case "C" ->
                DesignName.setText("Position: HR Clear");
            case "E" ->
                DesignName.setText("Position: Employee");
            default -> {
                DesignName.setText("");
            }
        }
    }//GEN-LAST:event_empdesignationActionPerformed

    private void EmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DepartCodeMsg;
    private javax.swing.JTextField DepartName;
    private javax.swing.JTextField DesignMsg;
    private javax.swing.JTextField DesignName;
    private javax.swing.JTextField EmployeeID;
    private javax.swing.JTextField EmployeeName;
    private javax.swing.JTextField Location;
    private javax.swing.JTextField LocationMsg;
    private javax.swing.JButton MainMenu;
    private javax.swing.JTextField NameMsg;
    private javax.swing.JButton Submit;
    private javax.swing.JComboBox<String> departcodelist;
    private javax.swing.JComboBox<String> empdesignation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
